kind: Namespace
apiVersion: v1
metadata:
  #name of the namespace we're creating
  name: nginx-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  #name of the deployment
  name: nginx-demo
  #previously created namespace that we'll be deploying to
  namespace: nginx-demo
  labels:
    app: nginx-demo
spec:
  #replicas specifies the number of pods to deploy
  replicas: 1
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
        #name of the container we'll use in our pod
        - name: nginx
          #specific image to deploy (in this case pulled from the public registry.k8s.io)
          image: nginx:1.27.0
          ports:
            #internal port to expose the container on
            - containerPort: 80
          volumeMounts:
            #this volumeMount will mount the configmap file we'll be creating next to customize our web page
            - name: nginx-config
              mountPath: /usr/share/nginx/html
      volumes:
        #defines the volume for the configmap we'll be creating next
        - name: nginx-config
          configMap:
            name: sample-page-1
---
#creates the nodeport service that we'll use to expose our pod to the extnernal network on port 30999
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo
  namespace: nginx-demo
spec:
  type: NodePort
  selector:
    app: nginx-demo
  ports:
    - port: 80
      nodePort: 30999
