#Confgure NTP Servers
apiVersion: esx.vmware.com/v1alpha1
kind: HostConfiguration
metadata:
  name: ntp-sync
  namespace: esx-system
spec:
  layertype: Incremental
  profile: |
    {
      "esx": {
        "system": {
          "system_time": {
            "enabled": true,
            "protocol": "NTP",
            "ntp_config": {
              "server": [{
                  "hostname": "0.pool.ntp.org",
                  "command": "SERVER"
                },
                {
                  "hostname": "1.pool.ntp.org",
                  "command": "SERVER"
                }
              ]
            }
          }
        }
      }
    }
---
#Example showing how to change the DCUI Welcome message
apiVersion: esx.vmware.com/v1alpha1
kind: HostConfiguration
metadata:
  name: welcome-message
  namespace: esx-system
spec:
  layertype: Incremental
  profile: |
    {
      "esx": {
          "system": {
            "welcome_message": {
                "message": "{align:left}{color:white} \n\n\n\n\tVECO Managed - Lab Infra Edge Host{/color}{/align}\n\n\n\n\n\n\n\n\n{align:left}{color:yellow} \tTo manage this host, go to: \n\thttps://{ip}/ (DHCP)\n\thttps://[fe80::8aae:ddff:fe0c:b382]/ (STATIC){/color}{/align}\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n{align:left}{color:yellow} <F2> Customize System/View Logs{/color}{/align}{align:right}{color:yellow} <F12> Shut Down/Restart{/color}{/align}"
            }
          }
      }
    }
---
#Example creating a read only account on the host for monitoring
apiVersion: esx.vmware.com/v1alpha1
kind: HostConfiguration
metadata:
  name: monitoring-user
  namespace: esx-system
spec:
  layertype: Incremental
  profile: |
    {
      "esx": {
        "authentication": {
          "user_accounts": [
            {
              "name": "monitor",
              "password_hash": "980e22233e336c3500fc5401a09af66262ddcf4188fc4df27118f60442821113321ab2ecfdf653b1c82705793a0fa1a54a68500ef19a4da3b83bcea7a1717be6",
              "description": "Monitoring user account"
            }
          ]
        },
        "authorization": {
          "permissions": [
            {
              "principal": "monitor",
              "is_group": false,
              "access_mode": "ReadOnly"
            }
          ]
        }
      }
    }