#Example showing how to enable add a new PG w/promiscuous mode and forged transmits
apiVersion: esx.vmware.com/v1alpha1
kind: HostConfiguration
metadata:
  name: vss-cfg-v1
  namespace: esx-system
spec:
  layertype: Incremental
  profile: |
    {
        "esx": {
            "network_vss": {
                "switches": [
                    {
                        "name": "vSwitch0",
                        "bridge": {
                            "link_discovery_protocol": {
                                "protocol": "CDP",
                                "operation": "LISTEN"
                            },
                            "nics": [
                                "vmnic0"
                            ]
                        },
                        "port_groups": [
                            {
                                "name": "Management Network",
                                "vlan_id": 0,
                                "policy": {
                                    "nic_teaming": {
                                        "policy": "LOADBALANCE_SRCID",
                                        "notify_switches": true,
                                        "rolling_order": false,
                                        "link_criteria_beacon": "IGNORE",
                                        "active_nics": [
                                            "vmnic0"
                                        ],
                                        "standby_nics": []
                                    }
                                }
                            },
                            {
                                "name": "VM Network",
                                "vlan_id": 0
                            },
                            {
                                "name": "TestPG",
                                "vlan_id": 0,
                                "policy": {
                                    "Security": {
                                        "allow_promiscuous": true,
                                        "mac_changes": true,
                                        "forged_transmits": true
                                    }
                                }
                            },
                            {
                                "name": "HomeAuto",
                                "vlan_id": 0,
                                "policy": {
                                    "Security": {
                                        "allow_promiscuous": true,
                                        "mac_changes": true,
                                        "forged_transmits": true
                                    }
                                }
                            }
                        ]                        
                    }
                ]
            }
        }
    }