#Confgure NTP Servers
apiVersion: esx.vmware.com/v1alpha1
kind: HostConfiguration
metadata:
  name: keswick-ntp-config
  namespace: esx-system
spec:
  layertype: Incremental
  profile: |
    {
      "esx": {
        "system": {
          "system_time": {
            "enabled": true,
            "protocol": "NTP",
            "ntp_config": {
              "server": [{
                  "hostname": "0.pool.ntp.org",
                  "command": "SERVER"
                },
                {
                  "hostname": "1.pool.ntp.org",
                  "command": "SERVER"
                }
              ]
            }
          }
        }
      }
    }
---
#Example showing how to change the DCUI Welcome message
apiVersion: esx.vmware.com/v1alpha1
kind: HostConfiguration
metadata:
  name: welcome-message
  namespace: esx-system
spec:
  layertype: Incremental
  profile: |
    {
      "esx": {
          "system": {
            "welcome_message": {
                "message": "{align:left}{color:white} \n\n\n\n\tVECO Managed - Hoffer Lab Infra Edge Host{/color}{/align}\n\n\n\n\n\n\n\n\n{align:left}{color:yellow} \tTo manage this host, go to: \n\thttps://{ip}/ (DHCP)\n\thttps://[fe80::8aae:ddff:fe0c:b382]/ (STATIC){/color}{/align}\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n{align:left}{color:yellow} <F2> Customize System/View Logs{/color}{/align}{align:right}{color:yellow} <F12> Shut Down/Restart{/color}{/align}"
            }
          }
      }
    }
---
#Example creating a read only account on the host for monitoring
apiVersion: esx.vmware.com/v1alpha1
kind: HostConfiguration
metadata:
  name: monitoring-user
  namespace: esx-system
spec:
  layertype: Incremental
  profile: |
    {
      "esx": {
        "authentication": {
          "user_accounts": [
            {
              "name": "testmon",
              "description": "Monitoring user account",
              "password_hash": "$6$0fuSsfbkjKeOqsw.$MSY9jjylwMBONfTejnt7tM3unRSECiomtaOnnmqQ0Dnxksc6SfaUswHp/8i6OhBkpha..z.iq/mhlgmVNjqak."
            }
          ]
        },
        "authorization": {
          "permissions": [
            {
              "principal": "testmon",
              "is_group": false,
              "access_mode": "ReadOnly"
            }
          ]
        }
      }
    }
---
#Example VSS with allow promiscuous, mac changes, and forged transmits
apiVersion: esx.vmware.com/v1alpha1
kind: HostConfiguration
metadata:
  name: vswitch-cfg
  namespace: esx-system
spec:
  layertype: Incremental
  profile: |
    {
      "esx": {
        "network_vss": {
          "switches": [
            {
              "name": "vSwitch0",
              "policy": {
                "security": {
                  "allow_promiscuous": false,
                  "mac_changes": false,
                  "forged_transmits": false
                }
              }
            }
          ]
        }
      }
    }
---