#Mint linux example
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: mint-for-grt
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: best-effort-large
  imageName: ent.box.com/shared/static/8v1kfawugxampu9g1d4txuzvg3tvb60x.ova
  powerState: poweredOn
  networkInterfaces:
  - networkName: "VM Network"
    ethernetCardType: "vmxnet3"
  vmMetadata:
    configMapName: user-data-mint
    transport: CloudInit
  configSpec:
    cpuAffinity: [0-4]
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: user-data-mint
    namespace: default
data:
  user-data: |
    #cloud-config
    package_update: true
    packages:
      - lib32stdc++6
    runcmd:
      - dpkg --add-architecture i386